version: '3.9'
services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql-main
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    ports:
      - '43306:3306'
    environment:
      MYSQL_DATABASE: 'main'
      MYSQL_USER: 'main_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'main-mysql:/var/lib/mysql'
      - 'main-mysql:/logs'
      - 'main-mysql:/etc/mysql/conf.d'
    networks:
      - public-service-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u main_user", "-p password" ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    container_name: redis-main
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    ports:
      - '46379:6379'
    volumes:
      - 'main-redis:/data'
    networks:
      - public-service-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    container_name: phpmyadmin
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PMA_HOST: mysql-main
      PMA_PORT: '43306'
      PMA_USER: 'root'
      PMA_PASSWORD: 'password'
      UPLOAD_LIMIT: 128M
    restart: always
    depends_on:
      - mysql
      - nginx
    networks:
      - public-service-network
    ports:
      - "18080:80"
    volumes:
      - "main-phpmyadmin:/sessions"
      - "~/docker/phpmyadmin/configs:/etc/phpmyadmin/"
      - "./phpmyadmin/custom-themes/:/var/www/html/themes/"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-main
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'main-nginx:/etc/nginx/certs'
      - './nginx/site-enabled/:/etc/nginx/conf.d/'
      - 'main-nginx:/etc/nginx/common.conf/'
      - './nginx/certificates/:/etc/nginx/ssl/'
      - './nginx/settings/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - public-service-network
networks:
  public-service-network:
    name: 'public-service-network'
    driver: bridge
volumes:
  main-mysql:
    driver: local
  main-redis:
    driver: local
  main-nginx:
    driver: local
  main-phpmyadmin:
    driver: local
