server {
	listen 80 default_server;
	listen [::]:80 default_server;

	set $forward_scheme "http";
	set $server "127.0.0.1";
	set $port "80";

	server_name localhost;

	error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

	location / {
		index index.html;
		root /usr/share/nginx/html;
	}
}