import { mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { Command } from 'commander';
import { UserError, color, say } from '../ui.js';

export type Shell = 'bash' | 'zsh' | 'fish';

export interface CommandSpec {
  name: string;
  description: string;
  /** Completes container/service names as its first argument. */
  takesService: boolean;
  subcommands: Array<{ name: string; description: string }>;
}

/**
 * Derived from the commander tree rather than hand-maintained.
 *
 * v1 shipped three static completion files that had to be edited in lockstep
 * with the CLI; they drifted more than once. Generating them removes the class
 * of bug entirely.
 */
export function specsFrom(program: Command): CommandSpec[] {
  return program.commands
    .filter((cmd) => !(cmd as unknown as { _hidden?: boolean })._hidden)
    .map((cmd) => ({
      name: cmd.name(),
      description: cmd.description(),
      takesService: cmd.registeredArguments.some((a) => a.name() === 'service'),
      subcommands: cmd.commands.map((sub) => ({
        name: sub.name(),
        description: sub.description(),
      })),
    }));
}

const escape = (s: string): string => s.replace(/'/g, "'\\''");

function bashScript(specs: CommandSpec[]): string {
  const names = specs.map((s) => s.name).join(' ');
  const withService = specs.filter((s) => s.takesService).map((s) => s.name);
  const withSubs = specs.filter((s) => s.subcommands.length > 0);

  const subCases = withSubs
    .map((s) => `        ${s.name}) opts="${s.subcommands.map((x) => x.name).join(' ')}" ;;`)
    .join('\n');

  return `# pubservices bash completion (generated by: pubservices completion bash)
_pubservices() {
    local cur prev words cword
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    local commands="${names}"
    local services="mysql redis postgres nginx phpmyadmin pgadmin mailpit minio"

    if [[ $COMP_CWORD -eq 1 ]]; then
        mapfile -t COMPREPLY < <(compgen -W "$commands" -- "$cur")
        return
    fi

    local opts=""
    case "\${COMP_WORDS[1]}" in
${subCases}
        ${withService.join('|')}) opts="$services" ;;
    esac

    if [[ -n "$opts" && $COMP_CWORD -eq 2 ]]; then
        mapfile -t COMPREPLY < <(compgen -W "$opts" -- "$cur")
        return
    fi

    mapfile -t COMPREPLY < <(compgen -W "--help --json --yes --home" -- "$cur")
    [[ "$prev" == "--home" ]] && mapfile -t COMPREPLY < <(compgen -d -- "$cur")
}
complete -F _pubservices pubservices
`;
}

function zshScript(specs: CommandSpec[]): string {
  const commands = specs.map((s) => `        '${s.name}:${escape(s.description)}'`).join('\n');

  const subBlocks = specs
    .filter((s) => s.subcommands.length > 0)
    .map(
      (s) => `            ${s.name})
                _values 'subcommand' ${s.subcommands.map((x) => `'${x.name}'`).join(' ')}
                ;;`,
    )
    .join('\n');

  const serviceBlock = specs.filter((s) => s.takesService).map((s) => s.name).join('|');

  return `#compdef pubservices
# generated by: pubservices completion zsh

_pubservices() {
    local -a commands
    commands=(
${commands}
    )

    if (( CURRENT == 2 )); then
        _describe 'command' commands
        return
    fi

    if (( CURRENT == 3 )); then
        case "\${words[2]}" in
${subBlocks}
            ${serviceBlock})
                _values 'service' mysql redis postgres nginx phpmyadmin pgadmin mailpit minio
                ;;
        esac
        return
    fi

    _arguments '--help[show help]' '--json[machine-readable output]' \
        '--yes[skip confirmations]' '--home[state directory]:path:_directories'
}

_pubservices "$@"
`;
}

function fishScript(specs: CommandSpec[]): string {
  const lines = [
    '# pubservices fish completion (generated by: pubservices completion fish)',
    'complete -c pubservices -f',
    '',
  ];

  for (const s of specs) {
    lines.push(
      `complete -c pubservices -n '__fish_use_subcommand' -a '${s.name}' -d '${escape(s.description)}'`,
    );
  }
  lines.push('');

  for (const s of specs) {
    for (const sub of s.subcommands) {
      lines.push(
        `complete -c pubservices -n '__fish_seen_subcommand_from ${s.name}' -a '${sub.name}' -d '${escape(sub.description)}'`,
      );
    }
  }
  lines.push('');

  const serviceCommands = specs.filter((s) => s.takesService).map((s) => s.name);
  if (serviceCommands.length > 0) {
    lines.push(
      `complete -c pubservices -n '__fish_seen_subcommand_from ${serviceCommands.join(' ')}' -a 'mysql redis postgres nginx phpmyadmin pgadmin mailpit minio' -d 'service'`,
    );
  }

  lines.push('');
  lines.push("complete -c pubservices -l json -d 'machine-readable output'");
  lines.push("complete -c pubservices -l yes -s y -d 'skip confirmations'");
  lines.push("complete -c pubservices -l home -r -d 'state directory'");
  lines.push('');
  return lines.join('\n');
}

export function renderCompletion(shell: Shell, specs: CommandSpec[]): string {
  if (shell === 'bash') return bashScript(specs);
  if (shell === 'zsh') return zshScript(specs);
  return fishScript(specs);
}

/** User-owned locations only — installing completions must never need root. */
export function completionTarget(shell: Shell): { dir: string; file: string; note?: string } {
  const home = homedir();
  const xdgData = process.env['XDG_DATA_HOME'] ?? join(home, '.local', 'share');

  if (shell === 'bash') {
    return {
      dir: join(xdgData, 'bash-completion', 'completions'),
      file: 'pubservices',
      note: 'Loaded automatically by bash-completion 2.x. Start a new shell to pick it up.',
    };
  }
  if (shell === 'zsh') {
    const dir = join(xdgData, 'zsh', 'site-functions');
    return {
      dir,
      file: '_pubservices',
      note: `If completion does not appear, add to ~/.zshrc:\n    fpath=(${dir} $fpath)\n    autoload -Uz compinit && compinit`,
    };
  }
  return {
    dir: join(process.env['XDG_CONFIG_HOME'] ?? join(home, '.config'), 'fish', 'completions'),
    file: 'pubservices.fish',
    note: 'Loaded automatically by fish. Start a new shell to pick it up.',
  };
}

function detectShell(): Shell {
  const shell = process.env['SHELL'] ?? '';
  if (shell.includes('zsh')) return 'zsh';
  if (shell.includes('fish')) return 'fish';
  return 'bash';
}

export function completionPrint(shellArg: string | undefined, specs: CommandSpec[]): void {
  const shell = parseShell(shellArg ?? detectShell());
  process.stdout.write(renderCompletion(shell, specs));
}

export function completionInstall(shellArg: string | undefined, specs: CommandSpec[]): void {
  const shells: Shell[] = shellArg ? [parseShell(shellArg)] : ['bash', 'zsh', 'fish'];

  say.blank();
  for (const shell of shells) {
    const { dir, file, note } = completionTarget(shell);
    mkdirSync(dir, { recursive: true });
    const path = join(dir, file);
    writeFileSync(path, renderCompletion(shell, specs));
    say.ok(`${color.bold(shell)}  ${path}`);
    if (note) say.meta(`  ${note}`);
  }
  say.blank();
}

function parseShell(value: string): Shell {
  if (value === 'bash' || value === 'zsh' || value === 'fish') return value;
  throw new UserError(`Unsupported shell: ${value}`, 'Supported: bash, zsh, fish');
}
